services:
  app:
    build: .
    container_name: products-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: operations
      DB_PORT: 3306
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: operations
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
